# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-action.json
---
name: Get staging configuration

description: Gets the staging configuration.

outputs:
    should-deploy-backend:
        description: Whether a backend stack should be deployed.
        value: ${{ steps.changed.outputs.backend }} == true ||  ${{ steps.changed.outputs.cdk }} == true

    api-endpoint:
        description: The API endpoint that the frontend should use.
        value: |
            (${{ steps.changed.outputs.backend }} == true ||  ${{ steps.changed.outputs.cdk }} == true) 
            && https://staging-${{ github.event.pull_request.number }}.api.antalmanac.com
            || https://dev.api.antalmanac.com

runs:
    using: composite

    steps:
        - name: Check for changes
          id: changed
          uses: dorny/paths-filter@v2
          with:
              filters: |
                  backend:
                    - 'apps/backend/**'
                  cdk:
                    - 'apps/cdk/**'
