# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Destroy CloudFormation stacks for staging environment

on:
    pull_request:
        types:
            - closed

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

permissions:
    id-token: write
    contents: read
    pull-requests: write
    deployments: write
    repository-projects: write

env:
    HUSKY: 0
    NODE_ENV: staging

    # Backend environment variables.
    HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
    CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
    MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}

    # Turborepo credentials.
    TURBO_API: ${{ vars.TURBO_API }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: team_antalmanac

jobs:
    destroy_staging_frontend:
        name: Destroy staging frontend CloudFormation stack and environment

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js and pnpm
              uses: ./.github/actions/setup-node-and-pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build frontend
              uses: pnpm --filter "antalmanac" build
              env:
                  VITE_ENDPOINT: ${{ needs.get_staging_configuration.outputs.api-endpoint }}

            - name: Destroy staging frontend CloudFormation stack
              run: pnpm --filter "antalmanac-cdk" staging-frontend destroy

            - name: Delete frontend staging URL
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: staging url
                  delete: true

            - name: Deactivate frontend staging environment
              uses: strumwolf/delete-deployment-environment@195215d2c5602aee6fb4b9cf0853970decca9e7a # v2.3.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                environment: staging-frontend-${{ github.event.pull_request.number }}
                onlyDeactivateDeployments: true

    destroy_staging_backend:
        name: Destroy staging backend CloudFormation stack and environment

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get staging configuration
              id: staging_config
              uses: ./.github/actions/get-staging-config

            - name: Setup Node.js and pnpm
              uses: ./.github/actions/setup-node-and-pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build backend
              uses: pnpm --filter "antalmanac-backend" build

            - name: Destroy staging backend CloudFormation stack
              run: pnpm --filter "antalmanac-cdk" staging-backend destroy

            - name: Deactivate backend staging environment
              uses: strumwolf/delete-deployment-environment@195215d2c5602aee6fb4b9cf0853970decca9e7a # v2.3.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                environment: staging-backend-${{ github.event.pull_request.number }}
                onlyDeactivateDeployments: true
