name: "Run Unit Tests"

on:
  pull_request:
    types: [ opened, synchronize, unlabeled ]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test project
        env:
          # for Turbo caching
          TURBO_API: ${{ vars.TURBO_API }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: "team_antalmanac"
        run: npx turbo test